name: Build Mega Drive ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Prepare SGDK project
        run: |
          mkdir -p src
          cp main.c src/main.c
          chmod -R 777 "$GITHUB_WORKSPACE"

      - name: Build Mega Drive ROM
        run: docker run --rm -v "$GITHUB_WORKSPACE:/src" ghcr.io/rhargreaves/docker-sgdk:v2.00

      - name: Find and rename ROM
        run: |
          ROM=$(find . -type f -name "rom.bin" | head -n 1)
          if [ -z "$ROM" ]; then
            echo "ERROR: rom.bin was not created"
            exit 1
          fi
          cp "$ROM" The_Lost_Chords_Feedback.bin

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: The_Lost_Chords_Feedback_ROM
          path: The_Lost_Chords_Feedback.bin
