name: Build Mega Drive ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Build Mega Drive ROM
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            ghcr.io/rhargreaves/docker-sgdk:v2.00 \
            make -f /sgdk/makefile.gen

      - name: Find and rename ROM
        run: |
          find . -type f -name "rom.bin" -print
          ROM=$(find . -type f -name "rom.bin" | head -n 1)
          if [ -z "$ROM" ]; then
            echo "ERROR: rom.bin was not created"
            exit 1
          fi
          cp "$ROM" The_Lost_Chords_Feedback.bin

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: The_Lost_Chords_Feedback_ROM
          path: The_Lost_Chords_Feedback.bin
